steps:
# Bước 1: Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/organica-repo-us/organica-app:$COMMIT_SHA'
  - '.'

# Bước 2: Push image
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/organica-repo-us/organica-app:$COMMIT_SHA'

images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/organica-repo-us/organica-app:$COMMIT_SHA'

options:
  machineType: 'E2_HIGHCPU_8'   # OK ở us-central1, quota cao
  logging: 'CLOUD_LOGGING_ONLY'
